#服务器端口配置
server:
  port: 8082
#
spring:
  datasource:
    url: jdbc:mysql://localhost/mall?useUnicode=true&characterEncoding=UTF-8
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:/mapper/*.xml
